# e2e test for example.com

name: CI for example.com site. 

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    e2e-test:
        # The type of runner that the job will run on
        name: Run playwright test
        runs-on: ubuntu-latest
       

        # Setup node
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 17
            - name: Install npm
              run: npm install --force
            - name: Install playwright 
              run: npx playwright install --force
            - name: Run tests
              run: npx playwright test sample.spec.js --project replay-chromium --reporter=@replayio/playwright/reporter,line 

            - name: Archive HTML Report on failure
              if: failure()
              uses: actions/upload-artifact@v1
              with:
                name: report
                path: ./tests/

            - name: Upload replays
              if: ${{ always() }}
              uses: replayio/action-upload@v0.4.4
              with:
                api-key: ${{ secrets.RECORD_REPLAY_API_KEY }}